@startuml
abstract class Handler
class ConcreteHandler1
class ConcreteHandler2
class Client

Client -right-> Handler
Handler <|-- ConcreteHandler1
Handler <|-- ConcreteHandler2
Handler <--o ConcreteHandler2

abstract class Handler {
  +HandleRequest()
}
class ConcreteHandler1 {
  +HandleRequest()
}
class ConcreteHandler2 {
  +HandleRequest()
}
@enduml
