@startuml
class Client
class Receiver
class Invoker
abstract class Command
class ConcreteCommand

Client -right-> Receiver
Invoker o-right-> Command
Command <|-- ConcreteCommand
Receiver <-- ConcreteCommand
Client ..> ConcreteCommand

abstract class Command {
  +execute()
}
class ConcreteCommand {
  -state
  +execute()
}

note right of ConcreteCommand::"execute"
  receiver.Action()
end note
@enduml
