@startuml
together {
  abstract class Mediator
  class ConcreteMediator
}
together {
  abstract class Collegue
  class ConcreteCollegue1
  class ConcreteCollegue2
}

Mediator <-- Collegue
Mediator <|-- ConcreteMediator

Collegue <|-- ConcreteCollegue1
Collegue <|-- ConcreteCollegue2
ConcreteMediator --> ConcreteCollegue1
ConcreteMediator --> ConcreteCollegue2

@enduml
