@startuml
together {
  abstract class Prototype
  class ConcretePrototype1
  class ConcretePrototype2
  class Client
}

Client "prototype" --> Prototype
Prototype <|-- ConcretePrototype1
Prototype <|-- ConcretePrototype2

class Client {
  +Operation()
}
abstract class Prototype {
  +Clone()
}
class ConcretePrototype1 {
  +Clone()
}
class ConcretePrototype2 {
  +Clone()
}

note left of Client::"Operation"
  p = prototype.Clone()
end note
note left of ConcretePrototype1::"Clone"
  return copy of this
end note
note right of ConcretePrototype2::"Clone"
  return copy of this
end note
@enduml
