@startuml

class Client
abstract class Target
class Adapter
class Adaptee

Client -right-> Target
Target <|-- Adapter
Adapter -right-> Adaptee

abstract class Target {
  +Request()
}
class Adapter {
  +Request()
}
class Adaptee {
  +SpecificRequest()
}

note left of Adapter::"Request"
  adaptee.SpecificRequest()
end note
@enduml
