@startuml
class Client
together {
  abstract class AbstractFactory
  class ConcreteFactory1
  class ConcreteFactory2
}
together {
  abstract class AbstractProductA
  class ProductA1
  class ProductA2
}
together {
  abstract class AbstractProductB
  class ProductB1
  class ProductB2
}

Client -right-> AbstractFactory
Client -down-> AbstractProductA
Client -down-> AbstractProductB

AbstractFactory <|-- ConcreteFactory1
' ProductA1 <.left. ConcreteFactory1
' ProductA2 <.left. ConcreteFactory2
' ProductB1 <.left. ConcreteFactory1
' ProductB2 <.left. ConcreteFactory2
AbstractFactory <|-- ConcreteFactory2

AbstractProductA <|-- ProductA1
AbstractProductA <|-- ProductA2

AbstractProductB <|-- ProductB1
AbstractProductB <|-- ProductB2

abstract class AbstractFactory {
  +CreateProductA()
  +CreateProductB()
}
class ConcreteFactory1 {
  +CreateProductA()
  +CreateProductB()
}
class ConcreteFactory2 {
  +CreateProductA()
  +CreateProductB()
}
@enduml
